// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6CP2M5vTB75J36S4BDpBu0lma_2zh6o',
    appId: '1:648739613171:web:47e68048df7d0608398a86',
    messagingSenderId: '648739613171',
    projectId: 'handyman-2be6d',
    authDomain: 'handyman-2be6d.firebaseapp.com',
    databaseURL: 'https://handyman-2be6d-default-rtdb.firebaseio.com',
    storageBucket: 'handyman-2be6d.appspot.com',
    measurementId: 'G-CD8B2J6PTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6I1YqhHl0FIG_VxmYrI1WqtAoEKMPapg',
    appId: '1:648739613171:android:c2efd0ca2b23e65d398a86',
    messagingSenderId: '648739613171',
    projectId: 'handyman-2be6d',
    databaseURL: 'https://handyman-2be6d-default-rtdb.firebaseio.com',
    storageBucket: 'handyman-2be6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR2gS9gu3qhFbcx8-fae7DG2POphY2Iio',
    appId: '1:648739613171:ios:bbe55aea4a50ece4398a86',
    messagingSenderId: '648739613171',
    projectId: 'handyman-2be6d',
    databaseURL: 'https://handyman-2be6d-default-rtdb.firebaseio.com',
    storageBucket: 'handyman-2be6d.appspot.com',
    iosBundleId: 'com.handyman.itm',
  );
}
